linters-settings:
  custom:
    reqfields:
      path: ./cmd/plugin/main.so
      description: Checks for unset required struct fields.
      original-url: github.com/colinking/go-reqfields

linters:
  enable:
    - reqfields
