linters-settings:
  custom:
    required:
      path: ./cmd/plugin/main.so
      description: Compile-time warnings for required fields.
      original-url: github.com/colinking/go-required

linters:
  enable:
    - required
